language: node_js
node_js:
- node
deploy:
  api_key:
    secure: NkPnJ3MNVDJrTB4wXfWDNcxaYE3I11wj5QNOiOpjWLZubOO7FGVaiAnvU5Skb8fnHmnQ3x3uId0/kpvwjhCtX/WdTgwJrwO2so4PZx0yvyls0BT1rGoWejNbizWr7AwHYl28h+T1yowhEUf87v8QDdXWZ+YBoWRgjTJh0ZioZpvYS5LbFaTBoaDSgtWhQdD4J9Mr96vUaPaIkt+z1n9QroeZ/AlX9rx3aihLD54eXHX02jthCEmRXcm17urZAnLB9UP4azcDgyRqK88SQWfu2MA/G9X5t/HLc8rinJHo8uuxiHkevUzgIcC1CnvWjaeXNaDaicTARpAWNKiAPMv2IiWbcnvZFTUTZN7qsokQ4vcBzuU8kgvC/YkxTZ3/xz0j9D3ad+AkCGogRI9UQoFoOj9fjDZoWOpZ1RY0oN0rW3J/97Obvd1oEB5km8QpTzVjtU/b2Ke6k0WWsP8loFrAL0CVQtFEi+UHtue9y/sz1ZzpWWddlGKgb8zQoRxd/U4gyYD6YdfdafRp6pwD985hXNH7Jr+DL7jr8a0nMLiZZDSHX4UjLegVUk6cvajqCnoj7N0Jxy7zyovNt7rSCh9CF1MeUMwMGYDxSorqbp1XaGl2Zc7zU48h/GkJLEIpaxi8wxSRc7UMgIK4BXL6y2+ZiEKwq5c5DsTwtTy1bYqhjpM=
